/**
 * @file firestore.js
 * @description Firestore CRUD helper module.
 *
 * All public functions handle both DEMO_MODE (mock data) and
 * real Firestore. In DEMO_MODE, data is persisted to sessionStorage
 * so state survives tab navigation within a session.
 */

import { DEMO_MODE, FB_SDK_VERSION, firebaseConfig } from './config.js';

// ─── Demo seed data ───────────────────────────────────────────────
export const MOCK_DOCTORS = [
  { uid: 'demo-doctor-001', name: 'Dr. Priya Mehta',   specialty: 'General Medicine', available: true },
  { uid: 'demo-doctor-002', name: 'Dr. Rajesh Kumar',  specialty: 'Cardiology',       available: true },
  { uid: 'demo-doctor-003', name: 'Dr. Sunita Verma',  specialty: 'Neurology',        available: true },
];

const MOCK_TRIAGE_RESULTS = [
  {
    id: 'triage-001',
    patientId: 'demo-patient-001',
    symptoms: 'I have a severe headache and my eyes are sensitive to light.',
    urgency: 'moderate',
    conditions: ['Migraine', 'Tension headache', 'Photophobia'],
    advice: 'Rest in a dark, quiet room and stay hydrated. Take an OTC analgesic if needed. See a doctor if symptoms worsen after 24 hours.',
    seeDoctor: true,
    disclaimer: 'AI-generated by VaidyaAI using Gemini 2.5 Pro. Not a medical diagnosis.',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

const MOCK_APPOINTMENTS_KEY = 'vaidyaai_appointments';
const MOCK_TRIAGE_KEY       = 'vaidyaai_triage';

function getMockAppointments() {
  try {
    const raw = sessionStorage.getItem(MOCK_APPOINTMENTS_KEY);
    return raw ? JSON.parse(raw) : [...seedAppointments()];
  } catch { return [...seedAppointments()]; }
}

function saveMockAppointments(appts) {
  sessionStorage.setItem(MOCK_APPOINTMENTS_KEY, JSON.stringify(appts));
}

function getMockTriage() {
  try {
    const raw = sessionStorage.getItem(MOCK_TRIAGE_KEY);
    return raw ? JSON.parse(raw) : [...MOCK_TRIAGE_RESULTS];
  } catch { return [...MOCK_TRIAGE_RESULTS]; }
}

function seedAppointments() {
  const now = new Date();
  const tomorrow = new Date(now); tomorrow.setDate(now.getDate() + 1);
  const nextWeek = new Date(now); nextWeek.setDate(now.getDate() + 7);

  return [
    {
      id: 'appt-001', patientId: 'demo-patient-001', doctorId: 'demo-doctor-001',
      doctorName: 'Dr. Priya Mehta', specialty: 'General Medicine',
      slot: tomorrow.toISOString().replace(/T.*/, 'T10:00:00Z'),
      status: 'confirmed', triageId: 'triage-001', notes: null,
      patientName: 'Arjun Sharma',
    },
    {
      id: 'appt-002', patientId: 'demo-patient-001', doctorId: 'demo-doctor-002',
      doctorName: 'Dr. Rajesh Kumar', specialty: 'Cardiology',
      slot: nextWeek.toISOString().replace(/T.*/, 'T14:30:00Z'),
      status: 'pending', triageId: null, notes: null,
      patientName: 'Arjun Sharma',
    },
  ];
}

// ─── Firestore initialiser ────────────────────────────────────────
let _db = null;
async function getDb() {
  if (DEMO_MODE) return null;
  if (_db) return _db;
  const base = `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}`;
  const { getFirestore } = await import(`${base}/firebase-firestore.js`);
  // App already initialised by auth.js (singleton via initializeApp)
  const { getApp } = await import(`${base}/firebase-app.js`);
  _db = getFirestore(getApp());
  return _db;
}

// ─── Public API ───────────────────────────────────────────────────

/**
 * Fetch all doctors (for the booking wizard).
 * @returns {Promise<Array<{uid,name,specialty,available}>>}
 */
export async function getDoctors() {
  if (DEMO_MODE) return MOCK_DOCTORS;

  const db = await getDb();
  const { collection, query, where, getDocs } = await import(
    `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}/firebase-firestore.js`
  );
  const q = query(collection(db, 'users'), where('role', '==', 'doctor'));
  const snap = await getDocs(q);
  return snap.docs.map(d => ({ uid: d.id, ...d.data() }));
}

/**
 * Fetch appointments for a given user.
 * @param {string} userId
 * @param {'patient'|'doctor'} role
 * @returns {Promise<Array>}
 */
export async function getAppointments(userId, role) {
  if (DEMO_MODE) {
    const all = getMockAppointments();
    const field = role === 'doctor' ? 'doctorId' : 'patientId';
    return all.filter(a => a[field] === userId).sort((a, b) => new Date(a.slot) - new Date(b.slot));
  }

  const db = await getDb();
  const { collection, query, where, getDocs, orderBy } = await import(
    `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}/firebase-firestore.js`
  );
  const field = role === 'doctor' ? 'doctorId' : 'patientId';
  const q = query(collection(db, 'appointments'), where(field, '==', userId), orderBy('slot', 'asc'));
  const snap = await getDocs(q);
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}

/**
 * Fetch triage results for the current patient.
 * @param {string} patientId
 * @returns {Promise<Array>}
 */
export async function getTriageResults(patientId) {
  if (DEMO_MODE) {
    return getMockTriage().filter(t => t.patientId === patientId);
  }

  const db = await getDb();
  const { collection, query, where, getDocs, orderBy } = await import(
    `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}/firebase-firestore.js`
  );
  const q = query(
    collection(db, 'triage_results'),
    where('patientId', '==', patientId),
    orderBy('createdAt', 'desc')
  );
  const snap = await getDocs(q);
  return snap.docs.map(d => ({ id: d.id, ...d.data() }));
}

/**
 * Save a triage result locally (demo mode only; real mode = Cloud Run writes).
 * @param {object} triageData
 * @returns {string} the triage ID
 */
export function saveMockTriage(triageData) {
  const id = `triage-${Date.now()}`;
  const existing = getMockTriage();
  existing.unshift({ id, ...triageData, createdAt: new Date().toISOString() });
  sessionStorage.setItem(MOCK_TRIAGE_KEY, JSON.stringify(existing));
  return id;
}

/**
 * Save a new appointment (demo mode).
 * @param {object} apptData
 * @returns {string} appointment ID
 */
export function saveMockAppointment(apptData) {
  const id = `appt-${Date.now()}`;
  const existing = getMockAppointments();
  existing.push({ id, ...apptData, status: 'confirmed', createdAt: new Date().toISOString() });
  saveMockAppointments(existing);
  return id;
}

/**
 * Update appointment status and optional notes.
 * @param {string} apptId
 * @param {{status?: string, notes?: string}} updates
 * @returns {Promise<void>}
 */
export async function updateAppointment(apptId, updates) {
  if (DEMO_MODE) {
    const all = getMockAppointments();
    const idx = all.findIndex(a => a.id === apptId);
    if (idx !== -1) { all[idx] = { ...all[idx], ...updates }; saveMockAppointments(all); }
    return;
  }

  const db = await getDb();
  const { doc, updateDoc, serverTimestamp } = await import(
    `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}/firebase-firestore.js`
  );
  await updateDoc(doc(db, 'appointments', apptId), { ...updates, updatedAt: serverTimestamp() });
}

/**
 * Update user profile fields.
 * @param {string} uid
 * @param {object} fields
 * @returns {Promise<void>}
 */
export async function updateUserProfile(uid, fields) {
  if (DEMO_MODE) {
    const raw = sessionStorage.getItem('vaidyaai_demo_user');
    if (raw) {
      const user = JSON.parse(raw);
      sessionStorage.setItem('vaidyaai_demo_user', JSON.stringify({ ...user, ...fields }));
    }
    return;
  }

  const db = await getDb();
  const { doc, updateDoc } = await import(
    `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}/firebase-firestore.js`
  );
  await updateDoc(doc(db, 'users', uid), fields);
}

/**
 * Subscribe to real-time appointment queue updates for a doctor.
 * Returns an unsubscribe function. In DEMO_MODE, calls callback once with mock data.
 * @param {string} doctorId
 * @param {function} callback - called with Array of appointments
 * @returns {Promise<function>} unsubscribe
 */
export async function subscribeToQueue(doctorId, callback) {
  if (DEMO_MODE) {
    const appts = getMockAppointments().filter(a => a.doctorId === doctorId);
    callback(appts);
    return () => {}; // no-op unsubscribe
  }

  const db = await getDb();
  const { collection, query, where, onSnapshot, orderBy } = await import(
    `https://www.gstatic.com/firebasejs/${FB_SDK_VERSION}/firebase-firestore.js`
  );
  const today = new Date(); today.setHours(0,0,0,0);
  const q = query(
    collection(db, 'appointments'),
    where('doctorId', '==', doctorId),
    where('status', 'in', ['pending', 'confirmed']),
    orderBy('slot', 'asc')
  );
  return onSnapshot(q, (snap) => {
    callback(snap.docs.map(d => ({ id: d.id, ...d.data() })));
  });
}
