/**
 * @file symptom.js
 * @description Symptom Checker UI module — patient-facing star feature.
 *
 * Handles the symptom input form, Cloud Run API call (or mock),
 * and rendering of the triage result card with urgency badge.
 * Uses aria-live region for accessible loading/result announcements.
 */

import { getIdToken } from './auth.js';
import { CLOUD_RUN_BASE_URL, DEMO_MODE } from './config.js';
import { saveMockTriage } from './firestore.js';

// ─── Mock triage responses ────────────────────────────────────────
const MOCK_RESPONSES = {
  high: {
    urgency: 'high', seeDoctor: true,
    conditions: ['Hypertensive crisis', 'Migraine with aura', 'Ocular migraine'],
    advice: 'Seek immediate medical attention. Do not drive or operate machinery.',
  },
  moderate: {
    urgency: 'moderate', seeDoctor: true,
    conditions: ['Tension headache', 'Dehydration', 'Viral fever'],
    advice: 'Rest, stay hydrated, and take an OTC analgesic if needed. See a doctor if symptoms persist beyond 24 hours.',
  },
  low: {
    urgency: 'low', seeDoctor: false,
    conditions: ['Mild muscle soreness', 'Fatigue', 'Minor strain'],
    advice: 'Rest and gentle stretching should help. Ensure you are staying hydrated.',
  },
};

const DISCLAIMER = 'AI-generated by VaidyaAI using Gemini 2.5 Pro. Not a medical diagnosis. Always consult a qualified healthcare professional.';

const URGENCY_CONFIG = {
  low:      { icon: '✓',  label: 'Low — Self-care',  cls: 'badge--low',      card: 'triage-card--low' },
  moderate: { icon: '!',  label: 'Moderate — See Doctor', cls: 'badge--moderate', card: 'triage-card--moderate' },
  high:     { icon: '‼',  label: 'High — Urgent',   cls: 'badge--high',     card: 'triage-card--high' },
};

// ─── DOM refs (populated in init) ────────────────────────────────
let _form, _textarea, _charCount, _loadingEl, _resultEl, _liveRegion, _submitBtn;
let _debounceTimer = null;
const MAX_CHARS = 2000;

/**
 * Initialise the Symptom Checker for a page.
 * @param {{userId: string}} options
 */
export function initSymptomChecker({ userId }) {
  _form      = document.getElementById('symptom-form');
  _textarea  = document.getElementById('symptom-input');
  _charCount = document.getElementById('symptom-char-count');
  _loadingEl = document.getElementById('symptom-loading');
  _resultEl  = document.getElementById('symptom-result');
  _liveRegion = document.getElementById('symptom-live');
  _submitBtn = document.getElementById('symptom-submit');

  if (!_form || !_textarea) return;

  // Character counter with debounce
  _textarea.addEventListener('input', () => {
    clearTimeout(_debounceTimer);
    const len = _textarea.value.length;
    _charCount.textContent = `${len} / ${MAX_CHARS}`;
    if (len > MAX_CHARS) {
      _charCount.style.color = 'var(--c-accent)';
      _submitBtn.disabled = true;
    } else {
      _charCount.style.color = '';
      _submitBtn.disabled = false;
    }
  });

  _form.addEventListener('submit', (e) => {
    e.preventDefault();
    handleSubmit(userId);
  });
}

/** @param {string} userId */
async function handleSubmit(userId) {
  const symptoms = _textarea.value.trim();
  if (!symptoms) {
    _textarea.focus();
    return;
  }

  setLoading(true);
  clearResult();

  try {
    let triage;
    const useMock = !CLOUD_RUN_BASE_URL || sessionStorage.getItem('vaidyaai_demo_user');
    if (useMock) {
      triage = await mockTriageCall(symptoms);
      triage.triageId = saveMockTriage({ patientId: userId, symptoms, ...triage, disclaimer: DISCLAIMER });
    } else {
      triage = await realTriageCall(symptoms);
    }
    renderTriageCard(triage);
  } catch (err) {
    showError(err.message || 'An error occurred. Please try again.');
  } finally {
    setLoading(false);
  }
}

/** Simulate AI delay and return a mock triage based on keywords */
async function mockTriageCall(symptoms) {
  await new Promise(r => setTimeout(r, 1800)); // simulate latency
  const lower = symptoms.toLowerCase();
  let key = 'moderate';
  if (/chest pain|can't breathe|difficulty breathing|unconscious|stroke|vision loss|severe/.test(lower)) key = 'high';
  else if (/tired|sore|slight|mild|minor/.test(lower)) key = 'low';
  return { ...MOCK_RESPONSES[key], disclaimer: DISCLAIMER };
}

/** Call the real Cloud Run endpoint */
async function realTriageCall(symptoms) {
  const token = await getIdToken();
  const res = await fetch(`${CLOUD_RUN_BASE_URL}/symptom-check`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
    body: JSON.stringify({ symptoms }),
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error || `Server error: ${res.status}`);
  return data;
}

/** Render the triage result card */
function renderTriageCard(triage) {
  const cfg = URGENCY_CONFIG[triage.urgency] || URGENCY_CONFIG.moderate;
  const conditionTags = (triage.conditions || [])
    .map(c => `<span class="condition-tag">${escapeHtml(c)}</span>`).join('');

  _resultEl.innerHTML = `
    <div class="triage-card ${cfg.card} animate-fade-in" role="region" aria-label="Triage Result">
      <div class="triage-card__header">
        <span class="triage-card__title">AI Triage Result</span>
        <span class="badge ${cfg.cls}" role="status" aria-label="Urgency level: ${cfg.label}">
          <span class="badge__icon" aria-hidden="true">${cfg.icon}</span>
          ${escapeHtml(cfg.label)}
        </span>
      </div>

      <div class="triage-card__section">
        <div class="triage-card__section-label">Possible Conditions</div>
        <div class="triage-card__conditions">${conditionTags}</div>
      </div>

      <div class="triage-card__section">
        <div class="triage-card__section-label">Recommended Action</div>
        <p class="triage-card__advice">${escapeHtml(triage.advice)}</p>
      </div>

      ${triage.seeDoctor ? `
        <div class="triage-card__section">
          <div class="triage-card__section-label">Doctor Visit</div>
          <p style="color:var(--c-accent);font-family:var(--font-mono);font-size:var(--text-sm);font-weight:600;">
            ⚕ Please book an appointment with a doctor.
          </p>
        </div>` : ''}

      <p class="triage-card__disclaimer">${escapeHtml(triage.disclaimer)}</p>
    </div>`;

  if (_liveRegion) {
    _liveRegion.textContent = `Triage complete. Urgency level: ${cfg.label}. ${triage.advice}`;
  }
  _resultEl.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

function setLoading(on) {
  _submitBtn.setAttribute('data-loading', String(on));
  _submitBtn.disabled = on;
  _loadingEl.setAttribute('data-visible', String(on));
  if (_liveRegion && on) _liveRegion.textContent = 'Analysing your symptoms with Gemini AI…';
}

function clearResult() { _resultEl.innerHTML = ''; }

function showError(msg) {
  _resultEl.innerHTML = `
    <div class="auth-alert" data-visible="true" role="alert">
      <strong>Error:</strong> ${escapeHtml(msg)}
    </div>`;
  if (_liveRegion) _liveRegion.textContent = `Error: ${msg}`;
}

/** Safe HTML escape */
function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
