'use strict';

/**
 * @file routes/symptomCheck.js
 * @description POST /symptom-check
 *
 * Validates the Firebase ID token, sanitises input, calls Vertex AI
 * Gemini 2.5 Pro with a structured system prompt, writes the result
 * to Firestore, and returns the triage JSON to the client.
 *
 * Request body:
 *   { symptoms: string }   — plain text, Hindi / English / Hinglish accepted
 *
 * Response 200:
 *   { triageId, urgency, conditions[], advice, seeDoctor, disclaimer }
 *
 * Errors:
 *   401 — missing / invalid auth token
 *   400 — empty or too-long symptoms
 *   503 — Vertex AI unavailable
 */

const express      = require('express');
const sanitizeHtml = require('sanitize-html');
const { VertexAI } = require('@google-cloud/vertexai');
const admin        = require('firebase-admin');
const { verifyFirebaseToken } = require('../middleware/auth');

const router = express.Router();

// ── Vertex AI configuration ────────────────────────────────────
const PROJECT_ID  = process.env.VERTEX_AI_PROJECT_ID || '';
const LOCATION    = process.env.VERTEX_AI_LOCATION   || 'us-central1';
const MODEL       = process.env.GEMINI_MODEL         || 'gemini-2.5-pro';

const SYSTEM_PROMPT = `You are VaidyaAI, an intelligent medical triage assistant.
Your role is to pre-assess patient symptoms and return a structured JSON response.

STRICT OUTPUT FORMAT — return ONLY valid JSON, no markdown, no explanation:
{
  "urgency": "low" | "moderate" | "high",
  "conditions": string[],
  "advice": string,
  "seeDoctor": boolean
}

RULES:
1. Never provide a definitive medical diagnosis.
2. conditions[] must contain 2–4 possible conditions only.
3. advice must be 1–2 sentences, actionable and clear.
4. Set urgency "high" and seeDoctor true for: chest pain, difficulty breathing,
   severe headache with vision changes, loss of consciousness, or stroke-like symptoms.
5. If symptoms are unclear or ambiguous, default to urgency "moderate".
6. Always recommend consulting a qualified doctor for moderate and high urgency.
7. Accept symptoms in Hindi, English, or Hinglish — always respond in English.`;

const DISCLAIMER =
  'AI-generated by VaidyaAI using Gemini 2.5 Pro. Not a medical diagnosis. Always consult a qualified healthcare professional.';

const MAX_INPUT_LENGTH = 2000;

/**
 * Sanitise raw user input: strip all HTML/script tags, trim whitespace.
 * @param {string} input
 * @returns {string}
 */
function sanitiseInput(input) {
  return sanitizeHtml(String(input), { allowedTags: [], allowedAttributes: {} }).trim();
}

/**
 * Call Vertex AI Gemini and return parsed triage JSON.
 * @param {string} sanitisedSymptoms
 * @returns {Promise<{urgency,conditions,advice,seeDoctor}>}
 */
async function callGemini(sanitisedSymptoms) {
  const vertexAI = new VertexAI({ project: PROJECT_ID, location: LOCATION });

  const model = vertexAI.getGenerativeModel({
    model: MODEL,
    generationConfig: {
      temperature: 0.2,
      maxOutputTokens: 512,
      responseMimeType: 'application/json',
    },
    systemInstruction: { parts: [{ text: SYSTEM_PROMPT }] },
  });

  const result = await model.generateContent({
    contents: [{ role: 'user', parts: [{ text: `Patient symptoms: ${sanitisedSymptoms}` }] }],
  });

  const text = result.response.candidates?.[0]?.content?.parts?.[0]?.text || '{}';
  return JSON.parse(text);
}

/**
 * POST /symptom-check
 * @param {import('express').Request}  req
 * @param {import('express').Response} res
 */
async function handleSymptomCheck(req, res) {
  const rawSymptoms = req.body?.symptoms;

  // ── Input validation ─────────────────────────────────────────
  if (!rawSymptoms || typeof rawSymptoms !== 'string' || rawSymptoms.trim().length === 0) {
    return res.status(400).json({ error: 'symptoms field is required and cannot be empty.' });
  }

  const sanitised = sanitiseInput(rawSymptoms);

  if (sanitised.length > MAX_INPUT_LENGTH) {
    return res.status(400).json({
      error: `Symptom description is too long. Maximum ${MAX_INPUT_LENGTH} characters allowed.`,
    });
  }

  // ── Call Vertex AI ───────────────────────────────────────────
  let triage;
  try {
    triage = await callGemini(sanitised);
  } catch (err) {
    // Do not expose internal error to client
    console.error('[symptom-check] Gemini error:', err.message);
    return res.status(503).json({ error: 'AI service temporarily unavailable. Please try again shortly.' });
  }

  // ── Validate Gemini response shape ───────────────────────────
  const validUrgencies = ['low', 'moderate', 'high'];
  if (!validUrgencies.includes(triage.urgency)) triage.urgency = 'moderate';
  if (!Array.isArray(triage.conditions) || triage.conditions.length === 0) {
    triage.conditions = ['Unspecified condition'];
  }
  triage.conditions = triage.conditions.slice(0, 4);
  if (typeof triage.advice !== 'string') triage.advice = 'Please consult a healthcare professional.';
  if (typeof triage.seeDoctor !== 'boolean') triage.seeDoctor = triage.urgency !== 'low';

  // ── Write to Firestore ───────────────────────────────────────
  const db = admin.firestore();
  const triageRef = db.collection('triage_results').doc();

  await triageRef.set({
    patientId:  req.uid,
    symptoms:   sanitised,
    urgency:    triage.urgency,
    conditions: triage.conditions,
    advice:     triage.advice,
    seeDoctor:  triage.seeDoctor,
    createdAt:  admin.firestore.FieldValue.serverTimestamp(),
  });

  // ── Respond ──────────────────────────────────────────────────
  return res.status(200).json({
    triageId:   triageRef.id,
    urgency:    triage.urgency,
    conditions: triage.conditions,
    advice:     triage.advice,
    seeDoctor:  triage.seeDoctor,
    disclaimer: DISCLAIMER,
  });
}

router.post('/', verifyFirebaseToken, handleSymptomCheck);

// Export handler separately for unit testing
module.exports = router;
module.exports.handleSymptomCheck = handleSymptomCheck;
module.exports.sanitiseInput      = sanitiseInput;
module.exports.callGemini         = callGemini;
